# Generated by Django 4.0.5 on 2022-07-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=11)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
